### ISSUE TITLE
new install is missing on/off toggle

### ISSUE THREAD

**Issue by Stoner19** [rubycoinorg/traderdaddy#4]
New installs are missing the on/off button on the Dashboard. I have an existing TraderDaddy folder under application support so something from a previous install allows mine to work, but other users who are download 0.1.4 to use for the first time are missing the on/off button. 

![screen shot 2015-06-02 at 1 54 44 pm](https://cloud.githubusercontent.com/assets/8030643/7945604/0e92a176-092f-11e5-9866-e05a0abae8f4.png)

**Comment by FuzzyHobbit** [comment]
This issue has been fixed in v0.1.5, thanks!
